[package]
name = "pueue"
version = "3.4.0"
description = "A cli tool for managing long running shell commands."
keywords = ["shell", "command", "parallel", "task", "queue"]
readme = "../README.md"
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
anyhow = "1.0"
chrono = { workspace = true }
chrono-english = "0.1"
clap = { version = "4.5.1", features = ["derive", "cargo", "help"] }
clap_complete = "4.5.1"
clap_complete_nushell = "4.5.1"
comfy-table = "7"
command-group = { workspace = true }
ctrlc = { version = "3", features = ["termination"] }
handlebars = { workspace = true }
log = { workspace = true }
pest = "2.7"
pest_derive = "2.7"
pueue-lib = { version = "0.26.0", path = "../pueue_lib" }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
shell-escape = "0.1"
simplelog = "0.12"
snap = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tempfile = "3"
tokio = { workspace = true }
lazy_static = "1.4.0"
nats = "0.24"
async-nats="0.34"
futures = "0.3"
uuid = { version = "1.8.0", features = ["v4"] }
local-ip-address = "0.6"
which = "6"

[dev-dependencies]
anyhow = { workspace = true }
assert_cmd = "2"
better-panic = { workspace = true }
# Make it easy to view log output for select tests.
# Set log level for tests with RUST_LOG=<level>, use with failed tests or
# disable test stdout/stderr capture (`cargo test -- --nocapture` / `cargo
# nextest run --no-capture`)
env_logger = "0.11"
pretty_assertions = { workspace = true }
rstest = "0.18"
serde_yaml = { workspace = true }
similar-asserts = "1"
test-log = "0.2"

# We don't need any of the default features for crossterm.
# However, the windows build needs the windows feature enabled.
[target.'cfg(not(windows))'.dependencies]
crossterm = { version = "0.27", default-features = false }
[target.'cfg(windows)'.dependencies]
crossterm = { version = "0.27", default-features = false, features = ["windows"] }

# Test specific dev-dependencies
[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
whoami = "1"
procfs = { version = "0.16", default-features = false }

