[package]
name = "pueue"
version = "3.4.1"
description = "A cli tool for managing long running shell commands."
keywords = ["shell", "command", "parallel", "task", "queue"]
readme = "../README.md"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
anyhow = "1.0"
chrono.workspace = true
clap = { version = "4.5", features = ["derive", "cargo", "help"] }
clap_complete = "4.5"
clap_complete_nushell = "4.5"
comfy-table = "7"
command-group.workspace = true
ctrlc = { version = "3", features = ["termination"] }
handlebars.workspace = true
interim = { version = "0.1.2", features = ["chrono"] }
log.workspace = true
pest = "2.7"
pest_derive = "2.7"
pueue-lib = { version = "0.26.1", path = "../pueue_lib" }
serde.workspace = true
serde_json.workspace = true
shell-escape = "0.1"
simplelog = "0.12"
snap.workspace = true
strum.workspace = true
tempfile = "3"
tokio = { workspace = true }
lazy_static = "1.5.0"
serde_derive="1"
nats = "0.25"
async-nats = "0.37"
futures = "0.3"
uuid = { version = "1.10.0", features = ["v4"] }
local-ip-address = "0.6"
which = "7"

[dev-dependencies]
anyhow.workspace = true
assert_cmd = "2"
assert_matches = "1"
better-panic.workspace = true
# Make it easy to view log output for select tests.
# Set log level for tests with RUST_LOG=<level>, use with failed tests or
# disable test stdout/stderr capture (`cargo test -- --nocapture` / `cargo
# nextest run --no-capture`)
env_logger = "0.11"
pretty_assertions.workspace = true
rstest = "0.23"
serde_yaml.workspace = true
similar-asserts = "1"
test-log = "0.2"

# We don't need any of the default features for crossterm.
# However, the windows build needs the windows feature enabled.
[target.'cfg(not(windows))'.dependencies]
crossterm = { version = "0.28", default-features = false }
[target.'cfg(windows)'.dependencies]
crossterm = { version = "0.28", default-features = false, features = [
    "windows",
] }
windows-service = "0.7.0"
windows = { version = "0.58.0", features = [
    "Win32_System_RemoteDesktop",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_SystemServices",
    "Win32_System_Environment",
] }

# Test specific dev-dependencies
[target.'cfg(any(target_os = "linux", target_os = "freebsd", target_os = "netbsd"))'.dependencies]
whoami = "1"

# Test specific Linux dev-dependencies
[target.'cfg(target_os = "linux")'.dependencies]
procfs = { version = "0.17", default-features = false }
